### ISSUE TITLE
Differences between resource type on the website and resource type that appears when generating

### ISSUE THREAD

**Issue by BFTnaito** [k1LoW/awsecrets#34]
I'd like to use awspec for testing AWS. I checked awspec resource type on the website (https://github.com/k1LoW/awspec/blob/master/doc/resource_types.md#resource-types). Then there is ecs resource, but when I generated, no ecs resource was available even though awspec version was latest 1.29.3.
Is there any reason why the resources on the website are not generated?

**Comment by k1LoW** [comment]
duplicate https://github.com/k1LoW/awspec/issues/588
